name: Docker

on:
  schedule:
    - cron: '17 18 * * *'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        if : github.event_name != 'pull_request'
        uses : sigstore/cosign-installer@v3.5.0 
        with :
          cosign-release : 'v2.2.4'

      - name : Set up Docker Buildx 
        uses : docker/setup-buildx-action@v3 

      - name : Log into registry ${{ env.REGISTRY }}
        if : github.event_name != 'pull_request'
        uses : docker/login-action@v3 
        with :
          registry   : ghcr.io # directly used here instead of env variable for clarity 
          username   : ${{ github.actor }}
          password   : ${{ secrets.GITHUB_TOKEN }}

      - name : Extract Docker metadata 
        id   : meta 
        uses    docker/metadata-action@v5 # using latest version 

      - name  Build and push Docker image  
       id    build-and-push    
       uses     docker/build-push-action@latest     # use latest stable version  
       with :
         tags         = ${{ steps.meta.outputs.tags }}   
         labels     = ${{ steps.meta.outputs.labels }}   
         context = .  
         push = ${{ github.event_name != 'pull_request' }}   
         cache-from = type=gha    
         cache-to = type=gha,mode=max  

        # Sign the published Docker image except on PRs  
          if:${{github.event_name!='pull_request'}}    
         env :
           TAGS:${{steps.meta.outputs.tags}}     
           DIGEST:${{steps.build-and-push.outputs.digest}}       
         run :"echo '${TAGS}' | xargs -I {} cosign sign --yes {} @${DIGEST}"    
